#!/bin/bash

banner() {
	clear	
	red="\e[1;91m"
	echo -e $red
	cat /$(whoami)/ccs/banner/banner.txt
	echo
	printf "\e[1;92;5m[\e[1;37;5m+\e[92m]\e[1;34;5m Script By : Albin Joseph C. R \e[0m\e[1;5m[ UCEH ]\e[0m"
	echo ""
}

menu() {
	echo ""
	printf " \e[1;31m[\e[0m\e[1;77m01\e[0m\e[1;31m]\e[0m\e[1;93m C \e[0m\n"
	printf " \e[1;31m[\e[0m\e[1;77m02\e[0m\e[1;31m]\e[0m\e[1;93m C + + \e[0m\n"
	
	echo ""
	read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' option
	echo ""
	if [[ $option == 1 || $option == 01 ]]; then
	c_code
	elif [[ $option == 2 || $option == 02 ]]; then	
	cpp_code
	fi
}

newFile() {
	blue="\e[1;34m"
	echo -e $blue
	
	read -p "Enter the name of the file: " input
	sudo mousepad "/$(whoami)/ccs/$input"
		
	read -p "Do you want to see the output?(y/n): " ch2
	if [ $ch2 == y || $ch2 == Y ]
	then

	read -p "Enter the Output File Name :" output	
	g++ $input -o $output
	sudo mv $output "/$(whoami)/ccs/Output/"
	cd "/$(whoami)/ccs/Output/"
	echo ""
	
	red="\e[1;91m"
	echo -e $red
	./$output
	fi

	if [ $ch2 == n || $ch2 == N]
	then
	exit 1
	fi
}

existingFile() {
	green="\e[1;32m"
	echo -e $green

	read -p "Enter the Input File Name :" input
	read -p "Enter the Output File Name :" output

	g++ $input -o $output

	sudo mv $output "/$(whoami)/ccs/Output/"
	cd "/$(whoami)/ccs/Output/"
	echo ""
	red="\e[1;91m"
	echo -e $red
	./$output
}

newFile_c() {
	blue="\e[1;34m"
	echo -e $blue
	
	read -p "Enter the name of the file: " input_c
	sudo mousepad "/$(whoami)/ccs/$input_c"
		
	read -p "Do you want to see the output?(y/n): " ch4
	if [ $ch4 == y || $ch4 == Y]
		then

		read -p "Enter the Output File Name :" output_c	
		gcc $input_c -o $output_c
		
		sudo mv $output_c "/$(whoami)/ccs/Output/"
		cd "/$(whoami)/ccs/Output/"
		echo ""
	
		red="\e[1;91m"
		echo -e $red
		./$output_c
	fi

	if [ $ch4 == n || $ch4 == N]
		then
		exit 1
	fi
}

existingFile_c() {
	green="\e[1;32m"
	echo -e $green

	read -p "Enter the Input File Name :" input_c
	read -p "Enter the Output File Name :" output_c

	gcc $input_c -o $output_c

	sudo mv $output_c "/$(whoami)/ccs/Output/"
	cd "/$(whoami)/ccs/Output/"
	echo ""
	red="\e[1;91m"
	echo -e $red
	./$output_c
}

cpp_code() {
	orange="\e[1;93m"
	echo -e $orange

	cd "/$(whoami)/ccs/" &>/dev/null # C++ File Location
	echo "Do you want to create new .cpp file?(y/n)"
	sleep 0.1
	read -p "Type 'n' to run existing .cpp file: " ch1 

	if [ $ch1 == y || $ch1 == Y]
		then
		newFile
	fi

	if [ $ch1 == n || $ch1 == N]
		then
		existingFile
	fi
}

c_code() {
	orange="\e[1;93m"
	echo -e $orange

	cd "/$(whoami)/ccs/" &>/dev/null # C File Location
	echo "Do you want to create new .c file?(y/n)"
	sleep 0.1
	read -p "Type 'n' to run existing .c file: " ch3 

	if [ $ch3 == y || $ch3 == Y]
		then
		newFile_c
	fi

	if [ $ch3 == n || $ch3 == N]
		then
		existingFile_c
	fi
}

banner
menu

